import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import PrelineScript from "@/components/PrelineScript";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={`${GeistSans.variable} ${GeistMono.variable}`} lang="en">
      <body>{children}</body>
      <PrelineScript />
    </html>
  );
}
